# This is a basic workflow that is manually triggered

name: My workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: camilakbn/docker-actions@v1
        with:
          who-to-greet: Camila Nascimento
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "A hora capturada foi ${{ steps.hello.outputs.time }}"
